In [47]:
import pandas as pd
import numpy as np
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import seaborn as sns
import matplotlib.pyplot as plt
import researchpy

data = pd.read_csv('atp_matches_2015.csv')
data.head()

def plot_winner_loser_stat(data,stat):
    winner_series=data["w_"+stat].to_list()
    loser_series=data["l_"+stat].to_list()
    #data[['w_'+stat, 'l_'+stat]].plot(kind='box', title='boxplot')
    result = researchpy.ttest(data["w_"+stat], data["l_"+stat])
    print(result)

plot_winner_loser_stat(data,"ace")

data['w_ace'].min()



(   Variable       N      Mean        SD        SE  95% Conf.  Interval
0     w_ace  2620.0  7.773664  6.293775  0.122959   7.532557  8.014771
1     l_ace  2620.0  5.590840  5.173115  0.101065   5.392664  5.789015
2  combined  5240.0  6.682252  5.862716  0.080990   6.523477  6.841027,               Independent t-test    results
0  Difference (w_ace - l_ace) =      2.1828
1          Degrees of freedom =   5238.0000
2                           t =     13.7143
3       Two side test p value =      0.0000
4      Difference < 0 p value =      1.0000
5      Difference > 0 p value =      0.0000
6                   Cohen's d =      0.3789
7                   Hedge's g =      0.3789
8               Glass's delta =      0.3468
9                 Pearson's r =      0.1862)


0.0

In [48]:
#one-hot encoding for surface
underground = data['surface']
values = array(underground)

label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)

onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

inverted = label_encoder.inverse_transform([argmax(onehot_encoded[2497, :])])

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 ...
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
